dist: trusty
services:
  - docker
env:
  TRAVIS_BRANCH_CLEAN=$(sed 's/\//-/g' <<< $TRAVIS_BRANCH)
  DOCKER_TAG="$TRAVIS_COMMIT.$TRAVIS_BRANCH_CLEAN"
  APP_NAME=ava-slackbot
script: |
  set -e

  docker build --tag imageintelligence/$APP_NAME:$DOCKER_TAG .
  if [ $TRAVIS_BRANCH = 'develop' ] || [ $TRAVIS_BRANCH = 'master' ]; then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    docker push imageintelligence/$APP_NAME:$DOCKER_TAG
  fi
